# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Screen-Exchange' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Screen-Exchange
  pod 'Money-FlightSchool', '~> 1.3.0'

  target 'Screen-ExchangeTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Screen-ExchangeUITests' do
    # Pods for testing
  end

end
